In [1]:
import pandas as pd
data={'Name':['Alice','bob'],'age':[20,23]}
df=pd.DataFrame(data)
print(df)

    Name  age
0  Alice   20
1    bob   23

In [2]:
df.iloc[1]

Name    bob
age      23
Name: 1, dtype: object

In [3]:
df.loc[0]

Name    Alice
age        20
Name: 0, dtype: object

In [4]:
df[df['age']<=20]

    Name  age
0  Alice   20

In [5]:
df['city']=['Tvm','banglr']
print(df)

    Name  age    city
0  Alice   20     Tvm
1    bob   23  banglr

In [6]:
df

    Name  age    city
0  Alice   20     Tvm
1    bob   23  banglr

In [7]:
new_rows=[
    ['Abel',21,'ptna'],
    ['Adhil',23,'ermli']
]
for row in new_rows:
    df.loc[len(df)] = row
df

    Name  age    city
0  Alice   20     Tvm
1    bob   23  banglr
2   Abel   21    ptna
3  Adhil   23   ermli

In [17]:
df.groupby('city')['age'].mean()

city
Tvm       20.0
banglr    23.0
ermli     23.0
ptna      21.0
Name: age, dtype: float64